services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "12345678"
      POSTGRES_DB: Exam
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d Exam"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./Backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./Backend/.env
    environment:
      DATABASE_URL: postgresql://postgres:12345678@db:5432/Exam
    volumes:
      - ./Backend:/app
      - /app/node_modules
    command: npm run dev:docker

  frontend:
    build: ./Frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    env_file:
      - ./Frontend/.env
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 5173

volumes:
  pgdata:
